export const PATH = {
  home: "/",
  cart: "/cart",
  productDetail: "/product/:id",
  login: "/login",
  register: "/register",
  profile: "/profile",
  adminDashboard: "/admin/dashboard",
  adminSupport: "/admin/support",
  adminProducts: "/admin/products",
  adminOrders: "/admin/orders",
  adminUsers: "/admin/users",
  orders: "/orders",
  orderDetail: "/orders/:id",
  checkout: "/checkout",
  category: "/category/:id",
  search: "/search",
  statisticsRevenue: "/statistics/revenue",
  statisticsOrders: "/statistics/orders",
  statisticsProducts: "/statistics/products",
  statisticsCustomers: "/statistics/customers",
  statisticsDetail: "/statistics/:type",
};
