export const PATH = {
  home: "/",
  cart: "/cart",
  productDetail: "/product/:id",
  login: "/login",
  register: "/register",
  adminDashboard: "/admin/dashboard",
  adminProducts: "/admin/products",
  adminOrders: "/admin/orders",
  adminUsers: "/admin/users",
  orders: "/orders",
  checkout: "/checkout",
  category: "/category/:id",
  search: "/search",
};
